# Generated by Django 5.0.2 on 2024-02-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
