# Generated by Django 5.0.2 on 2024-02-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0004_remove_profile_is_approved_profile_class_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='class_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text="Indicates if a teacher's account is approved. Ignored for other roles."),
        ),
    ]
