# Generated by Django 5.0.3 on 2024-04-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0006_profile_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Indicates a student's parent user account.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='user_portal.profile'),
        ),
    ]
