# Generated by Django 5.0.1 on 2024-03-27 14:36

import django.db.models.deletion
import edubridge_portal.models
import embed_video.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('definitions_choice', models.CharField(choices=[('NO', 'No'), ('UP', 'Upload a File')], default='NO', max_length=3)),
                ('definitions_upload', models.FileField(blank=True, upload_to='definitions_file/')),
                ('data', models.CharField(choices=[('VD', 'Video'), ('TX', 'Text'), ('IMG', 'Image')], default='', max_length=10)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('VD', 'Video'), ('TX', 'Text'), ('IMG', 'Image')], max_length=5, null=True)),
                ('video_data_choice', models.CharField(blank=True, choices=[('URL', 'URL'), ('UPLOAD', 'Upload video')], max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('SC', 'Single Choice'), ('CM', 'Comment'), ('SCA', 'Scale'), ('DD', 'Dropdown'), ('CB', 'Checkbox'), ('MCB', 'Multiple Checkbox')], default='', max_length=3)),
                ('is_required', models.BooleanField(default=False)),
                ('is_contingency', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='DropdownChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.question')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_file', models.FileField(default='', upload_to='data_file/')),
                ('token', models.CharField(default=edubridge_portal.models.generate_unique_token, max_length=10, unique=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='edubridge_portal.classroom')),
            ],
            options={
                'unique_together': {('classroom', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ImageDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='data_images/')),
                ('sr_number', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.classroom')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_data', to='edubridge_portal.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.sample')),
            ],
        ),
        migrations.CreateModel(
            name='ScalingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('min_description', models.CharField(max_length=254)),
                ('max_description', models.CharField(max_length=254)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.question')),
            ],
        ),
        migrations.CreateModel(
            name='TextDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('sr_number', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.classroom')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_data', to='edubridge_portal.sample')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswersSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answered', models.BooleanField(default=False)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_upload', embed_video.fields.EmbedVideoField()),
                ('sr_number', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.classroom')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_videos', to='edubridge_portal.sample')),
            ],
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.IntegerField(default=0)),
                ('video_url', models.CharField(max_length=1000)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.classroom')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='url_videos', to='edubridge_portal.sample')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=254, null=True)),
                ('answer_start_time', models.DateTimeField(blank=True, null=True)),
                ('answer_end_time', models.DateTimeField(blank=True, null=True)),
                ('checkboxAnswer', models.BooleanField(default=False)),
                ('answer', models.ManyToManyField(blank=True, related_name='answers', to='edubridge_portal.choice')),
                ('data_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.dataitem')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.enrollment')),
                ('image_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.imagedatatype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.question')),
                ('text_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.textdatatype')),
                ('user_answering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.videoupload')),
                ('video_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edubridge_portal.videourl')),
            ],
        ),
    ]
