# Generated by Django 5.0.1 on 2024-03-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubridge_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataitem',
            name='video_data_choice',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='data',
            field=models.CharField(choices=[('VDUR', 'Video'), ('VDUP', 'Video Upload'), ('TX', 'Text'), ('IMG', 'Image')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='data_type',
            field=models.CharField(choices=[('VDUR', 'Video'), ('VDUP', 'Video Upload'), ('TX', 'Text'), ('IMG', 'Image')], max_length=5, null=True),
        ),
    ]
