# Generated by Django 5.0.1 on 2024-04-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubridge_portal', '0003_remove_userresponse_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='video_upload',
            field=models.FileField(blank=True, upload_to='video_upload/'),
        ),
    ]
